services:
  app:
    build: .
    image: timesheet-manager:1.0
    container_name: timesheet-manager
    restart: unless-stopped
    volumes:
      - ./www:/var/www
      - ./server/php-local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network
    ports:
      - "9000:9000"
    depends_on:
      - db
      
  db:
    image: postgres:16.4-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - app_network

  certbot:
    image: certbot/certbot:v2.8.0
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./www:/var/www
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata:
